In [4]:
import os

print("Current working directory:")

print(os.getcwd())

print("\nFiles in current directory:")

print(os.listdir("."))

Current working directory:
/Users/utkarshbhadauria768/abes-rag-project/notebook

Files in current directory:
['data_exploration.ipynb']

In [5]:
from pathlib import Path

project_dir = Path.cwd().parent

file_path = (
    project_dir
    / "data"
    / "processed"
    / "extracted_documents.jsonl"
)

print("File exists:", file_path.exists())

File exists: True

In [6]:
import json
import pandas as pd

records = []

with file_path.open("r", encoding="utf-8") as file:
    for line in file:
        records.append(json.loads(line))

df = pd.DataFrame(records)

print("Dataset shape:", df.shape)
df.head()

Dataset shape: (5, 5)

,source_url,title,text,source_file,word_count
0,https://www.abes.ac.in/nirf-ranking-college.html,NIRF | ABESEC stands in the rank band of 201-2...,The National Institutional Ranking Framework (...,data/raw/html/6e594f211f344c3e4bb34886256e361c...,124
1,https://www.abes.ac.in/,"ABES Engineering College for B.Tech, M.Tech, M...",Clubs(Total 11 clubs)\nFuelling Ambitions & Fo...,data/raw/html/191ea43b28020b3cd86e2c3f59c8da91...,476
2,https://www.abes.ac.in/CAREER-department.html,CAREER-department ABES Engineering College Gha...,"ABES Engineering College, Ghaziabad provides a...",data/raw/html/1173c9e80277fd1cbc6623c8ee8cd540...,93
3,https://www.abes.ac.in/aaa-about-aaa.html,ABES Alumni Association ABES Engineering Colle...,About AAA\nFounded in 2007 and registered with...,data/raw/html/aad003c594c54d742bfe2c6e93a1de29...,1147
4,https://www.abes.ac.in/circulars.html,ABES Engineering College Ghaziabad | Ranked 1 ...,Circulars / Notices\nNotification regarding Su...,data/raw/html/0e153cfc08ba7a129326e418c5dc1009...,870

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   source_url   5 non-null      object
 1   title        5 non-null      object
 2   text         5 non-null      object
 3   source_file  5 non-null      object
 4   word_count   5 non-null      int64
dtypes: int64(1), object(4)
memory usage: 328.0+ bytes

In [8]:
df["word_count"].describe()

count       5.000000
mean      542.000000
std       462.139048
min        93.000000
25%       124.000000
50%       476.000000
75%       870.000000
max      1147.000000
Name: word_count, dtype: float64

In [9]:
df[["title", "word_count", "source_url"]].sort_values(

    by="word_count",

    ascending=True

)

,title,word_count,source_url
2,CAREER-department ABES Engineering College Gha...,93,https://www.abes.ac.in/CAREER-department.html
0,NIRF | ABESEC stands in the rank band of 201-2...,124,https://www.abes.ac.in/nirf-ranking-college.html
1,"ABES Engineering College for B.Tech, M.Tech, M...",476,https://www.abes.ac.in/
4,ABES Engineering College Ghaziabad | Ranked 1 ...,870,https://www.abes.ac.in/circulars.html
3,ABES Alumni Association ABES Engineering Colle...,1147,https://www.abes.ac.in/aaa-about-aaa.html

In [10]:
df.isnull().sum()

source_url     0
title          0
text           0
source_file    0
word_count     0
dtype: int64

In [11]:
print("Duplicate URLs:", df["source_url"].duplicated().sum())

print(

    "Duplicate text:",

    df["text"].duplicated().sum()

)

Duplicate URLs: 0
Duplicate text: 0

In [12]:
import json
import pandas as pd
from pathlib import Path

project_dir = Path.cwd().parent

cleaned_file = (
    project_dir
    / "data"
    / "processed"
    / "cleaned_documents.jsonl"
)

records = []

with cleaned_file.open(
    "r",
    encoding="utf-8"
) as file:

    for line in file:
        records.append(json.loads(line))

clean_df = pd.DataFrame(records)

print("Cleaned dataset shape:", clean_df.shape)

clean_df.head()

Cleaned dataset shape: (5, 7)

,source_url,title,text,source_file,word_count,character_count,content_hash
0,https://www.abes.ac.in/nirf-ranking-college.html,NIRF | ABESEC stands in the rank band of 201-2...,The National Institutional Ranking Framework (...,data/raw/html/6e594f211f344c3e4bb34886256e361c...,124,869,d9b47982450875b00060d62e4bf49b6e228b92f618f748...
1,https://www.abes.ac.in/,"ABES Engineering College for B.Tech, M.Tech, M...",Clubs(Total 11 clubs)\nFuelling Ambitions & Fo...,data/raw/html/191ea43b28020b3cd86e2c3f59c8da91...,476,3160,f07ec9d1f634a8b7e84176ec0959827b6d77b78606ff14...
2,https://www.abes.ac.in/CAREER-department.html,CAREER-department ABES Engineering College Gha...,"ABES Engineering College, Ghaziabad provides a...",data/raw/html/1173c9e80277fd1cbc6623c8ee8cd540...,93,608,028b61c3baad5603e7267b3475bc5b2dab466f0313ec45...
3,https://www.abes.ac.in/aaa-about-aaa.html,ABES Alumni Association ABES Engineering Colle...,About AAA\nFounded in 2007 and registered with...,data/raw/html/aad003c594c54d742bfe2c6e93a1de29...,1147,7437,dcac5b9e27369176f1724ed1103f3fa0ec7b25a819f13c...
4,https://www.abes.ac.in/circulars.html,ABES Engineering College Ghaziabad | Ranked 1 ...,Circulars / Notices\nNotification regarding Su...,data/raw/html/0e153cfc08ba7a129326e418c5dc1009...,870,6497,8a8eca1904c97288ba51e249ad6fc0e6d8bcab21be88ff...

In [13]:
clean_df[

    ["title", "word_count", "character_count"]

].sort_values(

    by="word_count",

    ascending=True

)

,title,word_count,character_count
2,CAREER-department ABES Engineering College Gha...,93,608
0,NIRF | ABESEC stands in the rank band of 201-2...,124,869
1,"ABES Engineering College for B.Tech, M.Tech, M...",476,3160
4,ABES Engineering College Ghaziabad | Ranked 1 ...,870,6497
3,ABES Alumni Association ABES Engineering Colle...,1147,7437

In [14]:
clean_df[

    ["source_url", "title", "text"]

].isnull().sum()

source_url    0
title         0
text          0
dtype: int64

In [16]:
import json
import pandas as pd
from pathlib import Path

project_dir = Path.cwd().parent

chunks_file = (
    project_dir
    / "data"
    / "processed"
    / "chunks.jsonl"
)

chunks = []

with chunks_file.open(
    "r",
    encoding="utf-8"
) as file:
    for line in file:
        chunks.append(json.loads(line))

chunks_df = pd.DataFrame(chunks)

print("Chunk dataset shape:", chunks_df.shape)

chunks_df.head()

Chunk dataset shape: (8, 7)

,chunk_id,source_url,title,chunk_index,start_word,end_word,text
0,63fa08e875fbbf724e9cd2ca71002bfde3c9347268584d...,https://www.abes.ac.in/nirf-ranking-college.html,NIRF | ABESEC stands in the rank band of 201-2...,0,0,124,The National Institutional Ranking Framework (...
1,31fe85506c3abb3cc5aea3b5baa9c4a429f3df71b4bd12...,https://www.abes.ac.in/,"ABES Engineering College for B.Tech, M.Tech, M...",0,0,476,Clubs(Total 11 clubs) Fuelling Ambitions & Fos...
2,b31393f3dabd9583edfa7b439350208e63a466c2131722...,https://www.abes.ac.in/CAREER-department.html,CAREER-department ABES Engineering College Gha...,0,0,93,"ABES Engineering College, Ghaziabad provides a..."
3,3f6fcdb62a601270d9f795a4e1e651eb1862ad486c4736...,https://www.abes.ac.in/aaa-about-aaa.html,ABES Alumni Association ABES Engineering Colle...,0,0,500,About AAA Founded in 2007 and registered with ...
4,0ae7e9e2903f47f9991286389a3bb94a51fc310036b0b0...,https://www.abes.ac.in/aaa-about-aaa.html,ABES Alumni Association ABES Engineering Colle...,1,400,900,ABES ALUMNI ASSOCIATION organized and sponsore...